### ISSUE TITLE
....

### ISSUE THREAD

**Issue by 289373410** [suxiongwei/lucene#8]
可以运行，但是查不到呀！不好使，代码运行过程中没错，就是查不到，可以加我qq指教我一二吗？谢谢！小白菜一个，希望得到大佬的帮忙！！！

**Comment by 289373410** [comment]
小弟qq289373110   叫人间蒸发！！

**Comment by suxiongwei** [comment]
搜索的前提是要生成索引文件，看看你本地索引生成的目录是否有索引文件

**Comment by 289373410** [comment]
哈哈，多谢老哥，还单独给我回复邮件，我已经找到问题在哪了，可以生成了！！多谢了！！！




------------------ 原始邮件 ------------------
发件人: "苏雄伟"<notifications@github.com>; 
发送时间: 2019年4月22日(星期一) 下午4:54
收件人: "suxiongwei/lucene"<lucene@noreply.github.com>; 
抄送: "炫ご儛灬奔"<289373410@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [suxiongwei/lucene] .... (#8)



搜索的前提是要生成索引文件，看看你本地索引生成的目录是否有索引文件
