### ISSUE TITLE
索引文件夹为空

### ISSUE THREAD

**Issue by zzpzbl** [suxiongwei/lucene#9]
![image](https://user-images.githubusercontent.com/51434091/102042536-07208200-3e0d-11eb-85a9-e92cf3ba7873.png)
我已经修改了 config.yml
而且终端打印创建索引成功
![image](https://user-images.githubusercontent.com/51434091/102042565-1acbe880-3e0d-11eb-8dc2-d7dfe1a8d28a.png)
但是搜索界面没有输入关键字没有结果
![image](https://user-images.githubusercontent.com/51434091/102042592-2fa87c00-3e0d-11eb-9a19-8c505165bff3.png)
请问还有什么配置需要修改

**Comment by zzpzbl** [comment]
![image](https://user-images.githubusercontent.com/51434091/102044032-efe39380-3e10-11eb-9007-9877ae2aeb82.png)
我将这里的index改成了变量indexpath，现在搜索功能有了，但是索引文件夹里面依然是空的，这一点我不是很明白

**Comment by zzpzbl** [comment]
已解决，是我找错位置了，抱歉

**Comment by suxiongwei** [comment]
哈哈 刚刚才看到您的邮件，这项目我写的学习的玩的，你可以在网上找找其它的资料，我这个老掉牙的项目好久没维护了，参考意义不高


| |
苏雄伟
|
|
xwsu512@126.com
|
签名由网易邮箱大师定制


在2020年12月15日 10:27，zzpzbl<notifications@github.com> 写道：

已解决，是我找错位置了，抱歉
